### ISSUE TITLE
请问看图说话的测试效果如何？

### ISSUE THREAD

**Issue by swordspoet** [bixiuping1999/ChatBot#1]
首先谢谢作者提供的中文标注数据，我用该数据集训练了一个模型，发现测试的效果不是很好，想问问作者测试出来的效果如何？用例二和用例三的结果还可以，用例一就完全不对。
用例一：
![image](https://user-images.githubusercontent.com/14816130/106453259-f9f64a00-64c3-11eb-9b18-17120cee9fa0.png)
![image](https://user-images.githubusercontent.com/14816130/106453277-ff539480-64c3-11eb-8441-82fc66eab3af.png)
用例二：
![image](https://user-images.githubusercontent.com/14816130/106453387-3629aa80-64c4-11eb-9676-f335de72ed2f.png)
![image](https://user-images.githubusercontent.com/14816130/106453409-3f1a7c00-64c4-11eb-9f86-ae58c088aa3a.png)
用例三：
![image](https://user-images.githubusercontent.com/14816130/106453451-50fc1f00-64c4-11eb-8151-1d946ce474a0.png)
![image](https://user-images.githubusercontent.com/14816130/106453473-59545a00-64c4-11eb-87f6-f181c0ae38f0.png)

**Comment by bixiuping1999** [comment]
你好，看图说话模型不是很好，只是当时异想天开加的一个功能，主要有两个原因，一是中文数据是根据英文谷歌机翻来的，里面有些句子意思相差较远，二是训练层数问题，当时本打算用GPTtransform模型来训练，后面没时间了。希望能给你一点启发



发自我的&nbsp;iPad


------------------ 原始邮件 ------------------
发件人: swordspoet <notifications@github.com&gt;
发送时间: 2021年2月1日 19:34
收件人: bixiuping1999/ChatBot <ChatBot@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[bixiuping1999/ChatBot] 请问看图说话的测试效果如何？ (#1)





 
首先谢谢作者提供的中文标注数据，我用该数据集训练了一个模型，发现测试的效果不是很好，想问问作者测试出来的效果如何？用例二和用例三的结果还可以，用例一就完全不对。
 用例一：
 
 
 用例二：
 
 
 用例三：

**Comment by swordspoet** [comment]
> 你好，看图说话模型不是很好，只是当时异想天开加的一个功能，主要有两个原因，一是中文数据是根据英文谷歌机翻来的，里面有些句子意思相差较远，二是训练层数问题，当时本打算用GPTtransform模型来训练，后面没时间了。希望能给你一点启发 发自我的&nbsp;iPad
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: swordspoet <notifications@github.com&gt; 发送时间: 2021年2月1日 19:34 收件人: bixiuping1999/ChatBot <ChatBot@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[bixiuping1999/ChatBot] 请问看图说话的测试效果如何？ (#1) 首先谢谢作者提供的中文标注数据，我用该数据集训练了一个模型，发现测试的效果不是很好，想问问作者测试出来的效果如何？用例二和用例三的结果还可以，用例一就完全不对。 用例一： 用例二： 用例三： — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

嗯嗯，多谢。从训练的过程来看，模型在训练的过程中过拟合很严重，现在尝试添加一下正则化试试。
